server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
#      defaultZone: http://45.119.84.194:40000/eureka
      defaultZone: http://103.48.192.223:40000/eureka